### ISSUE TITLE
Custom validators for account names

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation_auth#14]
- [ ] Don't allow slurs.
- [ ] Don't allow them to impersonate admins. 
- [ ] Style tags ("<" or ">")
- [ ] White space symbols like \n or \t

Any other idea?

**Comment by Fogapod** [comment]
Do you mean having `Admin` in name or you want to maintain db of all admin names? What about `Аdmin` ? (cyrillic `А`)
What about invisible unicode?

**Comment by corp-0** [comment]
yep, we can do that. Though basically all we need to avoid people impersonating admins is prohibiting brackets and tags symbols
