### ISSUE TITLE
Finish the account schema

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation_auth#2]
- [x] email: unique, not blank as login field
- [x] password: set basic password rules
- [x] account name: not unique, not blank
- [x] character settings: understand how the character serialization is done currently

Explore implementing these:
- [ ] account karma: numeric, let players reward other players with karma
- [ ] playtime per job
- [x] set some basic validations on account name to avoid gamer words

**Comment by Fogapod** [comment]
What about length restrictions for each field? At least max length

**Comment by corp-0** [comment]
The ones that are not explicitly declared are using the django default max length

**Comment by corp-0** [comment]
Character setting is stored as a json field, so whatever comes from the game, is stored as is. This is good because it is flexible and doesn't require any tinkering from our side, but it is also a black box and lacks validation.

**Comment by corp-0** [comment]
closing since the main stuff is done. Everything that we could add later is just ornamentation.
