### ISSUE TITLE
Reduce  docker the image size

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation_auth#3]
Right now we use the main [Python](https://hub.docker.com/_/python) image which is done with Ubuntu as a base, leaving us with around 1 GB of bloat. I tried doing the **Python:3.8-alpine** one but kept getting errors when installing dependencies.

Fix the issues and use alpine or find an option to reduce the image size as much as possible.

**Comment by Fogapod** [comment]
Assign me please

**Comment by corp-0** [comment]
done. Thank you very much.
